//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBankAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchanges
    {
        public int Id { get; set; }
        public string CurrencyCode { get; set; }
        public double ExchangeValue_USD { get; set; }
    }
}
